# Generated by Django 5.1 on 2024-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('estado', models.BooleanField(blank=True, default=False, null=True)),
                ('accion', models.CharField(blank=True, choices=[('PEN', 'PENDIENTE'), ('PRO', 'PROCESADO'), ('FIN', 'FINALIZADO'), ('CAN', 'CANCELADO')], db_column='accion', max_length=3, null=True, verbose_name='accion')),
                ('f_inicio', models.DateField(blank=True, db_column='f_inicio', null=True, verbose_name='fecha inicial')),
                ('f_fin', models.DateField(blank=True, db_column='f_fin', null=True, verbose_name='fecha fin')),
            ],
        ),
    ]
